import QtQuick
import QtQuick.Layouts
import Quickshell
import Quickshell.Io
import Quickshell.Widgets
import qs.config
import qs.modules.components
import qs.services
import qs.plugins

ContentMenu {
    title: "Appearance"
    description: "Adjust how the desktop looks."

    ContentCard {

        ColumnLayout {
            Layout.fillWidth: true
            spacing: Metrics.spacing(20)

            ColumnLayout {
                spacing: Metrics.spacing(6)

                StyledText {
                    text: "Theme"
                    font.pixelSize: Metrics.fontSize(18)
                    font.bold: true
                }

                StyledText {
                    text: "Choose between dark or light mode."
                    font.pixelSize: Metrics.fontSize(13)
                    opacity: 0.7
                }
            }

            RowLayout {
                Layout.fillWidth: true
                Layout.alignment: Qt.AlignHCenter
                spacing: Metrics.spacing(24)

                StyledButton {
                    Layout.preferredHeight: 200
                    Layout.preferredWidth: 260
                    Layout.maximumWidth: 320
                    Layout.fillWidth: true

                    icon: "dark_mode"
                    iconSize: Metrics.iconSize(56)
                    text: "Dark"

                    checked: Config.runtime.appearance.theme === "dark"
                    hoverEnabled: true

                    onClicked: {
                        if (!Config.runtime.appearance.colors.autogenerated) {
                            const scheme = Config.runtime.appearance.colors.scheme
                            const file = Theme.map[scheme]?.dark
                            if (!file) {
                                Theme.notifyMissingVariant(scheme, "dark")
                                return
                            }

                            Config.updateKey("appearance.theme", "dark")
                            Quickshell.execDetached([
                                "nucleus", "theme", "switch", file
                            ])
                        } else {
                            Config.updateKey("appearance.theme", "dark")
                            Quickshell.execDetached([
                                "nucleus", "ipc", "call", "global", "regenColors"
                            ])
                        }
                    }
                }

                StyledButton {
                    Layout.preferredHeight: 200
                    Layout.preferredWidth: 260
                    Layout.maximumWidth: 320
                    Layout.fillWidth: true

                    icon: "light_mode"
                    iconSize: Metrics.iconSize(56)
                    text: "Light"

                    checked: Config.runtime.appearance.theme === "light"
                    hoverEnabled: true

                    onClicked: {
                        if (!Config.runtime.appearance.colors.autogenerated) {
                            const scheme = Config.runtime.appearance.colors.scheme
                            const file = Theme.map[scheme]?.light
                            if (!file) {
                                Theme.notifyMissingVariant(scheme, "light")
                                return
                            }

                            Config.updateKey("appearance.theme", "light")
                            Quickshell.execDetached([
                                "nucleus", "theme", "switch", file
                            ])
                        } else {
                            Config.updateKey("appearance.theme", "light")
                            Quickshell.execDetached([
                                "nucleus", "ipc", "call", "global", "regenColors"
                            ])
                        }
                    }
                }
            }
        }
    }

    ContentCard {

        ColumnLayout {
            Layout.fillWidth: true
            spacing: Metrics.spacing(16)

            RowLayout {
                opacity: autogeneratedColorsSelector.enabled ? 1 : 0.7

                ColumnLayout {
                    spacing: Metrics.spacing(4)

                    StyledText {
                        text: "Generated Color Scheme"
                        font.pixelSize: Metrics.fontSize(16)
                        font.bold: true
                    }

                    StyledText {
                        text: "Scheme used when colors are autogenerated."
                        font.pixelSize: Metrics.fontSize(12)
                        opacity: 0.7
                    }
                }

                Item { Layout.fillWidth: true }

                StyledDropDown {
                    id: autogeneratedColorsSelector
                    label: "Scheme"

                    model: [
                        "scheme-content",
                        "scheme-expressive",
                        "scheme-fidelity",
                        "scheme-fruit-salad",
                        "scheme-monochrome",
                        "scheme-neutral",
                        "scheme-rainbow",
                        "scheme-tonal-spot"
                    ]

                    currentIndex: model.indexOf(Config.runtime.appearance.colors.matugenScheme)

                    onSelectedIndexChanged: (index) => {
                        if (!Config.runtime.appearance.colors.autogenerated)
                            return
                        const selectedScheme = model[index]
                        Config.updateKey("appearance.colors.matugenScheme", selectedScheme)
                        Quickshell.execDetached([
                            "nucleus", "ipc", "call", "global", "regenColors"
                        ])
                    }

                    enabled: Config.runtime.appearance.colors.autogenerated
                }
            }

            RowLayout {
                opacity: predefinedThemeSelector.enabled ? 1 : 0.7

                ColumnLayout {
                    spacing: Metrics.spacing(4)

                    StyledText {
                        font.pixelSize: Metrics.fontSize(16)
                        font.bold: true
                        text: "Predefined Theme"
                    }

                    StyledText {
                        font.pixelSize: Metrics.fontSize(12)
                        opacity: 0.7
                        text: "Choose a predefined interface theme."
                    }
                }

                Item { Layout.fillWidth: true }

                StyledDropDown {
                    id: predefinedThemeSelector
                    label: "Theme"
                    model: Object.keys(Theme.map)

                    currentIndex: model.indexOf(Config.runtime.appearance.colors.scheme)

                    onSelectedIndexChanged: (index) => {
                        if (Config.runtime.appearance.colors.autogenerated)
                            return

                        const selectedTheme = model[index]
                        const variant = Config.runtime.appearance.theme
                        const file = Theme.map[selectedTheme][variant]

                        if (!file) return

                        Config.updateKey("appearance.colors.scheme", selectedTheme)

                        Quickshell.execDetached([
                            "nucleus", "theme", "switch", file
                        ])
                    }

                    enabled: !Config.runtime.appearance.colors.autogenerated
                }
            }
        }
    }

    ContentCard {
        ColumnLayout {
            Layout.fillWidth: true
            spacing: Metrics.spacing(8)

            StyledSwitchOption {
                title: "Tint Icons"
                description: "Tint icons across the shell."
                prefField: "appearance.tintIcons"
            }

            StyledSwitchOption {
                title: "Autogenerated Themes"
                description: "Generate themes automatically."
                prefField: "appearance.colors.autogenerated"
            }

            StyledSwitchOption {
                title: "User Defined Themes"
                description: "Run matugen config from ~/.config/matugen."
                prefField: "appearance.colors.runMatugenUserWide"
            }
        }
    }

    ContentCard {

        StyledText {
            text: "Clock"
            font.pixelSize: Metrics.fontSize(20)
            font.bold: true
        }

        StyledSwitchOption {
            title: "Show Clock"
            description: "Show or hide the background clock."
            prefField: "appearance.background.clock.enabled"
        }

        StyledSwitchOption {
            title: "Analog Variant"
            description: "Use analog style clock."
            prefField: "appearance.background.clock.isAnalog"
        }

        StyledSwitchOption {
            title: "Rotate Clock Polygon"
            description: "Rotate the analog clock background."
            prefField: "appearance.background.clock.rotatePolygonBg"
            enabled: Config.runtime.appearance.background.clock.isAnalog
            opacity: enabled ? 1 : 0.7
        }

        NumberStepper {
            label: "Rotation Duration"
            description: "Time for one full rotation (seconds)."
            prefField: "appearance.background.clock.rotationDuration"
            minimum: 1
            maximum: 40
            step: 1
        }

        RowLayout {

            ColumnLayout {
                StyledText {
                    text: "Clock Shape"
                    font.pixelSize: Metrics.fontSize(16)
                    font.bold: true
                }

                StyledText {
                    text: "Shape of the analog clock."
                    font.pixelSize: Metrics.fontSize(12)
                    opacity: 0.7
                }
            }

            Item { Layout.fillWidth: true }

            StyledDropDown {
                label: "Shape"

                model: [
                    "Cookie 7 Sided",
                    "Cookie 9 Sided",
                    "Cookie 12 Sided",
                    "Pixelated Circle",
                    "Circle"
                ]

                currentIndex: Config.runtime.appearance.background.clock.shape

                onSelectedIndexChanged: (index) => {
                    Config.updateKey(
                        "appearance.background.clock.shape",
                        index
                    )
                }
            }
        }
    }

    ContentCard {

        StyledText {
            text: "Rounding"
            font.pixelSize: Metrics.fontSize(20)
            font.bold: true
        }

        NumberStepper {
            label: "Factor"
            description: "Adjust UI corner rounding."
            prefField: "appearance.rounding.factor"
            minimum: 0
            maximum: 1
            step: 0.1
        }
    }

    ContentCard {

        StyledText {
            text: "Font"
            font.pixelSize: Metrics.fontSize(20)
            font.bold: true
        }

        NumberStepper {
            label: "Scale"
            description: "Adjust global font scale."
            prefField: "appearance.font.scale"
            minimum: 0.1
            maximum: 2
            step: 0.1
        }
    }

    ContentCard {

        StyledText {
            text: "Transparency"
            font.pixelSize: Metrics.fontSize(20)
            font.bold: true
        }

        StyledSwitchOption {
            title: "Enabled"
            description: "Enable interface transparency."
            prefField: "appearance.transparency.enabled"
        }

        NumberStepper {
            label: "Alpha"
            description: "Transparency strength."
            prefField: "appearance.transparency.alpha"
            minimum: 0.1
            maximum: 1
            step: 0.1
        }
    }

    ContentCard {

        StyledText {
            text: "Animations"
            font.pixelSize: Metrics.fontSize(20)
            font.bold: true
        }

        StyledSwitchOption {
            title: "Enabled"
            description: "Enable shell animations."
            prefField: "appearance.animations.enabled"
        }

        NumberStepper {
            label: "Duration Scale"
            description: "Adjust animation speed."
            prefField: "appearance.animations.durationScale"
            minimum: 0.1
            maximum: 1
            step: 0.1
        }
    }
}
