// ~/.config/matugen/templates/colors.slint

export global Colors {
    // Primary
    out property <color> primary: #ffb692;
    out property <color> on-primary: #542103;
    out property <color> primary-container: #703717;
    out property <color> on-primary-container: #ffdbcb;
    out property <color> inverse-primary: #8d4e2c;

    // Secondary
    out property <color> secondary: #e6beac;
    out property <color> on-secondary: #432a1e;
    out property <color> secondary-container: #5c4033;
    out property <color> on-secondary-container: #ffdbcb;

    // Tertiary
    out property <color> tertiary: #d0c890;
    out property <color> on-tertiary: #353107;
    out property <color> tertiary-container: #4c481c;
    out property <color> on-tertiary-container: #ece4aa;

    // Error
    out property <color> error: #ffb4ab;
    out property <color> on-error: #690005;
    out property <color> error-container: #93000a;
    out property <color> on-error-container: #ffdad6;

    // Background
    out property <color> background: #1a120e;
    out property <color> on-background: #f0dfd8;

    // Surface
    out property <color> surface: #1a120e;
    out property <color> on-surface: #f0dfd8;

    out property <color> surface-variant: #52443d;
    out property <color> on-surface-variant: #d7c2b9;

    out property <color> surface-dim: #1a120e;
    out property <color> surface-bright: #423732;

    out property <color> surface-container-lowest: #140c09;
    out property <color> surface-container-low: #221a16;
    out property <color> surface-container: #271e19;
    out property <color> surface-container-high: #322823;
    out property <color> surface-container-highest: #3d332e;

    // Outline
    out property <color> outline: #a08d85;
    out property <color> outline-variant: #52443d;

    // Misc
    out property <color> shadow: #000000;
    out property <color> scrim: #000000;

    // Inverse
    out property <color> inverse-surface: #f0dfd8;
    out property <color> inverse-on-surface: #382e2a;

    // Fixed colors
    out property <color> primary-fixed: #ffdbcb;
    out property <color> primary-fixed-dim: #ffb692;
    out property <color> on-primary-fixed: #341100;
    out property <color> on-primary-fixed-variant: #703717;

    out property <color> secondary-fixed: #ffdbcb;
    out property <color> secondary-fixed-dim: #e6beac;
    out property <color> on-secondary-fixed: #2c160b;
    out property <color> on-secondary-fixed-variant: #5c4033;

    out property <color> tertiary-fixed: #ece4aa;
    out property <color> tertiary-fixed-dim: #d0c890;
    out property <color> on-tertiary-fixed: #1f1c00;
    out property <color> on-tertiary-fixed-variant: #4c481c;
}
